let assets = [
    // {
    //     assetName: "Chonkadonk",
    //     assetCategory:"Session",
    //     assetSubCategory:"Shootout",
    //     assetDescription:"",
    //     assetURL:"https://ronanarmstrong.com",
    // },
    {
        assetName: "Photopea",
        assetCategory:"Web Resource",
        assetSubCategory:"Web Apps",
        assetDescription:"A free online Photoshop alternative with an almost identical interface.",
        assetURL:"https://photopea.com",
    },
    {
        assetName: "Pixabay",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images, sound effects, and music.",
        assetURL:"https://pixabay.com/",
    },
    {
        assetName: "Pexels",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images and videos.",
        assetURL:"https://pexels.com/",
    },
    {
        assetName: "Carrd",
        assetCategory:"Web Resource",
        assetSubCategory:"Website Design",
        assetDescription:"Free online one page websites for portfolios, personal sites, and more.",
        assetURL:"https://carrd.co/",
    },
    {
        assetName: "Unsplash",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images and videos.",
        assetURL:"https://unsplash.com/",
    },
    {
        assetName: "Notion",
        assetCategory:"Web Resource",
        assetSubCategory:"Web Apps",
        assetDescription:"Workspace to create wikis, documents, and projects.",
        assetURL:"https://notion.so/",
    },
    {
        assetName: "Acustica",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"A variety of free analog-based plugins, including compression and EQ.",
        assetURL:"https://www.acustica-audio.com/shop",
    },
    {
        assetName: "Analog Obsession",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"Free plugin recreations of famous analog processors, including EQ and compression.",
        assetURL:"https://analogobsession.com/",
    },
    {
        assetName: "Melda FX",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"A variety of utility plugins, ranging from dynamic effects to metering.",
        assetURL:"https://www.meldaproduction.com/MFreeFXBundle",
    },
    {
        assetName: "Open Sound Meter",
        assetCategory:"Software",
        assetSubCategory:"Metering",
        assetDescription:"Free plugin recreations of famous analog processors, including EQ and compression.",
        assetURL:"https://analogobsession.com/",
    },
    {
        assetName: "Room EQ Wizard",
        assetCategory:"Software",
        assetSubCategory:"Metering",
        assetDescription:"Powerful acoustics measurement, prediction, and analysis software.",
        assetURL:"https://www.roomeqwizard.com/",
    },

]