let assets = [
    // {
    //     assetName: "Chonkadonk",
    //     assetCategory:"Session",
    //     assetSubCategory:"Shootout",
    //     assetDescription:"",
    //     assetURL:"https://ronanarmstrong.com",
    // },
    {
        assetName: "SMC Input Lists",
        assetCategory:"Web Resource",
        assetSubCategory:"SMC Tool",
        assetDescription:"A fillable PDF input list for the main studio at the SMC.",
        assetURL:"assets/SMC Input List Fillable.pdf",
    },
    {
        assetName: "Photopea",
        assetCategory:"Web Resource",
        assetSubCategory:"Web Apps",
        assetDescription:"A free online Photoshop alternative with an almost identical interface.",
        assetURL:"https://photopea.com",
    },
    {
        assetName: "Pixabay",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images, sound effects, and music.",
        assetURL:"https://pixabay.com/",
    },
    {
        assetName: "Pexels",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images and videos.",
        assetURL:"https://pexels.com/",
    },
    {
        assetName: "Carrd",
        assetCategory:"Web Resource",
        assetSubCategory:"Website Design",
        assetDescription:"Free online one page websites for portfolios, personal sites, and more.",
        assetURL:"https://carrd.co/",
    },
    {
        assetName: "Unsplash",
        assetCategory:"Web Resource",
        assetSubCategory:"Assets",
        assetDescription:"Royalty free stock images and videos.",
        assetURL:"https://unsplash.com/",
    },
    {
        assetName: "Notion",
        assetCategory:"Web Resource",
        assetSubCategory:"Web Apps",
        assetDescription:"Workspace to create wikis, documents, and projects.",
        assetURL:"https://notion.so/",
    },
    {
        assetName: "Acustica",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"A variety of free analog-based plugins, including compression and EQ.",
        assetURL:"https://www.acustica-audio.com/shop",
    },
    {
        assetName: "Analog Obsession",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"Free plugin recreations of famous analog processors, including EQ and compression.",
        assetURL:"https://analogobsession.com/",
    },
    {
        assetName: "Melda FX",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"A variety of utility plugins, ranging from dynamic effects to metering.",
        assetURL:"https://www.meldaproduction.com/MFreeFXBundle",
    },
    {
        assetName: "Open Sound Meter",
        assetCategory:"Software",
        assetSubCategory:"Metering",
        assetDescription:"Free plugin recreations of famous analog processors, including EQ and compression.",
        assetURL:"https://analogobsession.com/",
    },
    {
        assetName: "Room EQ Wizard",
        assetCategory:"Software",
        assetSubCategory:"Metering",
        assetDescription:"Powerful acoustics measurement, prediction, and analysis software.",
        assetURL:"https://www.roomeqwizard.com/",
    },
    {
        assetName: "ZenPro Clip-A-Lator",
        assetCategory:"Web Resource",
        assetSubCategory:"Shootout",
        assetDescription:"Massive gear shootout database, including microphones, preamps, and compressors.",
        assetURL:"https://www.zenproaudio.com/clipalator",
    },
    {
        assetName: "GuitarML",
        assetCategory:"Software",
        assetSubCategory:"Amp Simulator",
        assetDescription:"AI-powered guitar amp/stompbox simulator and capture tools.",
        assetURL:"https://guitarml.com/",
    },

    {
        assetName: "Vital",
        assetCategory:"Software",
        assetSubCategory:"Synth",
        assetDescription:"Powerful spectral wavetable synth, free or paid for advanced features.",
        assetURL:"https://vital.audio/",
    },
    {
        assetName: "TAL Software",
        assetCategory:"Software",
        assetSubCategory:"Instruments, Creative Effects, Vocoder",
        assetDescription:"A variety of lightweight and free synths, effects, and a great vocoder.",
        assetURL:"https://tal-software.com/products",
    },
    {
        assetName: "Spitfire Labs",
        assetCategory:"Software",
        assetSubCategory:"Instruments",
        assetDescription:"Sample-based instruments, including strings, pianos, and drums.",
        assetURL:"https://labs.spitfireaudio.com/",
    },
    {
        assetName: "U-He Triple Cheese",
        assetCategory:"Software",
        assetSubCategory:"Instruments",
        assetDescription:"Analog-inspired subtractive synth with built-in effects.",
        assetURL:"https://u-he.com/products/triplecheese/",
    },
    {
        assetName: "SSD 5.5 Free",
        assetCategory:"Software",
        assetSubCategory:"Instruments",
        assetDescription:"A limited version of the venerable SSD5 acoustic drum plugin.",
        assetURL:"https://stevenslatedrums.com/SSD5/#SSD5FREE",
    },
    {
        assetName: "Kilohearts",
        assetCategory:"Software",
        assetSubCategory:"Mixing",
        assetDescription:"A variety of free utility & creative plugins, including EQ, compression, and distortion.",
        assetURL:"https://kilohearts.com/products/kilohearts_essentials",
    },
    {
        assetName: "Ignite Amps",
        assetCategory:"Software",
        assetSubCategory:"Amp Simulator",
        assetDescription:"Solid collection of guitar amp simulators.",
        assetURL:"https://www.igniteamps.com/#software",
    },
    {
        assetName: "Blender",
        assetCategory:"Software",
        assetSubCategory:"3D Modeling/Animation",
        assetDescription:"Industry standard 3D modeling and animation software.",
        assetURL:"https://www.blender.org/",
    },
    {
        assetName: "Adobe Express",
        assetCategory:"Web Resource",
        assetSubCategory:"Graphics",
        assetDescription:"Easy-to-use tool to create posters, logos, and social media graphics.",
        assetURL:"https://www.adobe.com/express/",
    },
    {
        assetName: "Canva",
        assetCategory:"Web Resource",
        assetSubCategory:"Graphics",
        assetDescription:"Create posters, logos, and social media graphics with a variety of templates.",
        assetURL:"https://www.canva.com/",
    },
    {
        assetName: "Pixlr",
        assetCategory:"Web Resource",
        assetSubCategory:"Photo Editing",
        assetDescription:"Easy-to-use photo editor with a variety of filters and effects.",
        assetURL:"https://pixlr.com/",
    },
    {
        assetName: "Cloud Convert",
        assetCategory:"Web Resource",
        assetSubCategory:"File Conversion",
        assetDescription:"Convert audio, video, and image files to different formats.",
        assetURL:"https://cloudconvert.com/",
    },
    
    // {
    //     assetName: "Ignite",
    //     assetCategory:"Software",
    //     assetSubCategory:"Amp",
    //     assetDescription:"Solid",
    //     assetURL:"",
    // },
]