const mics = {
    //  "C414 XLII": {
    //     "manufacturer": "AKG",
    //     "polar": ["Cardioid", "Figure-8", "Omni", "Hemi"],
    //     "highestFreq": 20,
    //     "lowestFreq": 20,
    //     "SPL": 158,
    //     "hasPad": true,
    //     "type": "LDC",
    //     "lendingLevel": 4,
    //      "phantom": "YES",
    //     "uses": [
    //         "Acoustic Guitar",
    //         "Electric Guitar",
    //         "Electric Bass",
    //         "Vocals",
    //         "Acoustic Piano",
    //         "Violin/Viola/Cello",
    //         "Trumpet/Sax/Horns",
    //         "Drum Overheads",
    //         "Snare Drum",
    //         "Toms",
    //         "Hats/Cymbal Close Mics",
    //         "Kick",
    //         "Drum Room",
    //         "General Purpose"
    //     ],
    //     "char": [
    //         "Bright",
    //         "Transparent",
    //         "Dark",
    //         "Saturated",
    //         "Neutral",
    //         "Punchy",
    //         "Smooth",
    //     ],
    //     "img": "",
    // },
    "ETHOS": {
        "manufacturer": "Earthworks",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 30,
        "SPL": 145,
        "hasPad": false,
        "type": "LDC",
        "lendingLevel": 1,
        "phantom": "YES",
        "uses": [
            "Vocals",
        ],
        "char": [
            "Bright",
            "Transparent",
            "Neutral",
        ],
        "img": "https://v5.airtableusercontent.com/v1/15/15/1676577600000/WWPjm7WnA8jrXAsvVqPqzQ/xEGmEZrxtuYoE2QFtVyhw17PoZiu2oywpP_nR7zi_vYemjGwWPITELwAaILn5FS3ofcBIokzN-lnyva6H56sVA/xpB0pl2aeEXM4mP1H3Ls5dTDKYC5rdPup_PkPnCcg4k"
    },
     "QTC40": {
        "manufacturer": "Earthworks",
        "polar": ["Omni"],
        "highestFreq": 40,
        "lowestFreq": 3,
        "SPL": 140,
        "hasPad": false,
        "phantom":"YES",
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://v5.airtableusercontent.com/v1/15/15/1676577600000/lpFgYvAsw6szKDWw30F0Yg/Gv1XYZrVusH0JiT3vdjXcJaWkx70zQ0nyodLqGfa6_Xgl9g88cS_hQHIRXSF5TDxQ8uu3JyTGg4TSsnZlmkuIw/ERNkmiYoD9uR-0hRag_aheqNz3KIw-DBuwOdeUIqkuo",
    },
     "SR25": {
        "manufacturer": "Earthworks",
        "polar": ["Cardioid"],
        "highestFreq": 25,
        "lowestFreq": 20,
        "SPL": 145,
        "phantom":"YES",
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Electric Bass",
            "Kick",
        ],
        "char": [
            "Transparent",
            "Neutral",
            "Punchy",
        ],
        "img": "https://v5.airtableusercontent.com/v1/15/15/1676577600000/cHqrBYJ4lQXu8myfHJYzwA/vrgQbeBh8yHRiTt0sR-GOKAExuWHeMzVu9cYlBKJVpWqi0sCjpPiYgIv3Ipv_W8MGb0ZkS-4JSfprf40lba2NA/60pwghPqCj9m8kXZWTIlihgXbU4TYcFC3HtwLIHqv8A",
    },
    "LCT 441 FLEX": {
        "manufacturer": "Lewitt",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 144,
        "hasPad": false,
        "type": "LDC",
        "lendingLevel": "Unknown",
         "phantom": "YES",
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Punchy",
        ],
        "img": "https://v5.airtableusercontent.com/v1/15/15/1676577600000/2pBZa-7UIdL4zi0us7ulkA/vuVhunGjA6jE1YfCi0aypPYgKNkh2a4Hi9rTSptgIH5QUbgxdBADo-SUpCKA-HUWrXGpoqtNYuG3p-aJdtpk3Q/7W8TgEHjFmHGnUf4Dvj5XF0vjph6LdzXh-1oCa3_J_I",
    },
    
    "R44CE": {
        "manufacturer": "AEA",
        "polar": ["Figure-8"],
        "highestFreq": 20,
        "lowestFreq": 30,
        "phantom": "NO",
        "SPL": 140,
        "hasPad": false,
        "type": "Ribbon",
        "lendingLevel": 4,
        "uses": [
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room"
        ],
        "char": [
            "Dark",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/431daac993813feb8b4ffcb52a825771/f167ab35"
    },
    "R84": {
        "phantom": "NO",
        "manufacturer": "AEA",
        "polar": ["Figure-8"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 165,
        "hasPad": false,
        "type": "Ribbon",
        "lendingLevel": 4,
        "uses": [
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/d1f63968fef99b3c2f26a6726aacaa46/8454ffb3"
    },
    "C 451 B": {
        "phantom": "YES",
        "manufacturer": "AKG",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 155,
        "hasPad": true,
        "type": "SDC",
        "lendingLevel": 3,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Drum Overheads",
            "Snare Drum",
            "Hats/Cymbal Close Mics",
        ],
        "char": [
            "Bright",
            "Transparent",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/dc810b66e2e63fe194f31a07255ec1f9/2edeee87"
    },
    "C414 XLII": {
        "phantom": "YES",
        "manufacturer": "AKG",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 158,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Transparent",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/8cc6b9090c4ce14ed08c2ac55d47b3ca/b5dee810"
    },
    "C414 XLS": {
        "phantom": "YES",
        "manufacturer": "AKG",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 158,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 3,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Transparent",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/4b8ea8103c710d390309e18ab63dba15/17edbb80"
    },
    "D112 MKII": {
        "phantom": "NO",
        "manufacturer": "AKG",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 17,
        "SPL": 160,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 1,
        "uses": [
            "Electric Bass",
            "Kick",
        ],
        "char": [
            "Dark",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/fd217e5d1ec7d21446ea8f6d0788f8cb/03683d91"
    },
    "4006A": {
        "phantom": "YES",
        "manufacturer": "DPA",
        "polar": ["Omni"],
        "highestFreq": 20,
        "lowestFreq": 10,
        "SPL": 139,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/94fbc59c5769929e94765a27eac9034c/cd73c1cb"
    },
    "4011A": {
        "phantom": "YES",
        "manufacturer": "DPA",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 40,
        "SPL": 139,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": "Request",
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/4e65f7a3c5ca70d6b68c5b47404ec31c/5aefdaab"
    },
    "4099 Extreme SPL": {
        "phantom": "YES",
        "manufacturer": "DPA",
        "polar": ["Cardioid"],
        "highestFreq": 15,
        "lowestFreq": 80,
        "SPL": 137,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Trumpet/Sax/Horns",
            "Snare Drum",
            "Toms",
            "Hats/Cymbal Close Mics",
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/6610d1d0ad9e7ccb9f14662bb4a9a6b6/8bb08b30"
    },
    "4099 Loud SPL": {
        "phantom": "YES",
        "manufacturer": "DPA",
        "polar": ["Cardioid"],
        "highestFreq": 15,
        "lowestFreq": 9,
        "SPL": 131,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Toms",
            "Hats/Cymbal Close Mics",
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/439483123f70d59a69188cfb1eb63119/633a1b41"
    },
    "TC30K": {
        "phantom": "YES",
        "manufacturer": "Earthworks",
        "polar": ["Omni"],
        "highestFreq": 30,
        "lowestFreq": 9,
        "SPL": 150,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/290b3492ea5dfd07d27b228cf75882ac/9a2b3695"
    },
    "RE20": {
        "phantom": "NO",
        "manufacturer": "Electro-Voice",
        "polar": ["Cardioid"],
        "highestFreq": 18,
        "lowestFreq": 45,
        "SPL": 141,
        "hasPad": true,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Snare Drum",
            "Hats/Cymbal Close Mics",
            "Kick",
        ],
        "char": [
            "Dark",
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/ac93787d65629174be751754f6bd2be0/b0771e44"
    },
    "MA-201 FET": {
        "phantom": "YES",
        "manufacturer": "Mojave",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 125,
        "hasPad": false,
        "type": "LDC",
        "lendingLevel": 2,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/e0757ea4925c36ac6b2cb80087358c91/8c009856"
    },
    "KM130": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 140,
        "hasPad": true,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Saturated",
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/1adbe4b28334a265df9ebc6b1cbe792b/935887c9"
    },
    "KM143": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 138,
        "hasPad": true,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Saturated",
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/d2955d88b614d98febdcf9f379da0546/bf57f7e6"
    },
    "KM184": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 138,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 3,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/3e7981fa250cb35cf464b2ced2173f8c/2bdcd9cb"
    },
    "M149 Tube": {
        "phantom": "NO",
        "manufacturer": "Neumann",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 136,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Bass",
            "Vocals",
        ],
        "char": [
            "Saturated",
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/ffce745f0da2ad5b7cf4e0fece9b4ec4/1364ecf9"
    },
    "TLM49": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 110,
        "hasPad": false,
        "type": "LDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/e39f82cd71ad8f79472d34ec8c5c47de/7455b4c6"
    },
    "U47 FET": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Cardioid"],
        "highestFreq": 16,
        "lowestFreq": 40,
        "SPL": 137,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 4,
        "uses": [
            "Vocals",
            "Kick",
        ],
        "char": [
            "Bright",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/54d9f37e992d2fbbc4751ac11d49da56/90be851b"
    },
    "U87 Ai": {
        "phantom": "YES",
        "manufacturer": "Neumann",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 127,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": "Request",
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/3d5006e01d4bc216f102ba5d77f7f22e/68b0b9cb"
    },
    "NT5": {
        "phantom": "YES",
        "manufacturer": "Rode",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 143,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 2,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/777a60c00fba0db243e163f256286ea7/07eb868f"
    },
    "R10": {
        "phantom": "NO",
        "manufacturer": "Royer",
        "polar": ["Figure-8"],
        "highestFreq": 15,
        "lowestFreq": 30,
        "SPL": 160,
        "hasPad": false,
        "type": "Ribbon",
        "lendingLevel": 3,
        "uses": [
            "Electric Guitar",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
        ],
        "char": [
            "Dark",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/c2e0a8937bb72f4447aa46b7427523be/f2e74879"
    },
    "R121": {
        "phantom": "NO",
        "manufacturer": "Royer",
        "polar": ["Figure-8"],
        "highestFreq": 15,
        "lowestFreq": 30,
        "SPL": 135,
        "hasPad": false,
        "type": "Ribbon",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Room",
        ],
        "char": [
            "Saturated",
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/008c67dcca4717ff87d483c23bed79e2/a5bd60ce.png"
    },
    "CMC 6 MK4": {
        "phantom": "YES",
        "manufacturer": "Schoeps",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 131,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": "Request",
        "uses": [
            "Acoustic Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/8f9e734a122bda214cead2cfd8b83a84/b37af27d"
    },
    "e604": {
        "phantom": "NO",
        "manufacturer": "Sennheiser",
        "polar": ["Cardioid"],
        "highestFreq": 18,
        "lowestFreq": 40,
        "SPL":160,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Snare Drum",
            "Toms",
        ],
        "char": [
            "Dark",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/7527029a0e7e38767f055017f037b169/39a5502e"
    },
    "e901": {
        "phantom": "YES",
        "manufacturer": "Sennheiser",
        "polar": ["Hemi"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 154,
        "hasPad": false,
        "type": "Boundary Condenser",
        "lendingLevel": 3,
        "uses": [
            "Kick",
        ],
        "char": [
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/10b82ca28590a98ebe5b9506fd5db38c/c02c3b02"
    },
    "MD 421 II": {
        "phantom": "NO",
        "manufacturer": "Sennheiser",
        "polar": ["Cardioid"],
        "highestFreq": 17,
        "lowestFreq": 30,
        "SPL": 160,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 2,
        "uses": [
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Trumpet/Sax/Horns",
            "Snare Drum",
            "Toms",
            "Hats/Cymbal Close Mics",
            "Kick",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/cf8565b45a9f2af8a5489f4b840746fe/29fba3de"
    },
    "Beta 52A": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 10,
        "lowestFreq": 20,
        "SPL": 174,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 1,
        "uses": [
            "Electric Bass",
            "Kick",
        ],
        "char": [
            "Neutral",
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/2d38085b5b37c1047264fe9897a293c1/386932a4"
    },
    "Beta 56A": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 16,
        "lowestFreq": 50,
        "SPL": 200,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Electric Guitar",
            "Snare Drum",
            "Toms",
        ],
        "char": [
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/09384c05e21b2fdb9615b52280936817/b860e981"
    },
    "SM7B": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 50,
        "SPL": 180,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Electric Guitar",
            "Vocals",
            "Snare Drum",
            "Toms",
            "Hats/Cymbal Close Mics",
            "Kick",
            "General Purpose"
        ],
        "char": [
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/274760904c7ad359ad8257d6ad90142f/3532c398"
    },
    "SM57": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 15,
        "lowestFreq": 40,
        "SPL": 200,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 1,
        "uses": [
            "Electric Guitar",
            "Trumpet/Sax/Horns",
            "Snare Drum",
            "Toms",
            "Hats/Cymbal Close Mics",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/82398c73a7de866be6b863c775ef11ae/553f636d"
    },
    "SM58": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 15,
        "lowestFreq": 50,
        "SPL": 200,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 1,
        "uses": [
            "Electric Guitar",
            "Vocals",
            "Trumpet/Sax/Horns",
            "Snare Drum",
            "Toms",
            "Hats/Cymbal Close Mics",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/42c0872ff1d17afb24a161a2e0877aa8/981ddb5a"
    },
    "Super 55": {
        "phantom": "NO",
        "manufacturer": "Shure",
        "polar": ["Cardioid"],
        "highestFreq": 17,
        "lowestFreq": 60,
        "SPL": 200,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Vocals",
        ],
        "char": [
            "Dark",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/161d29a45465b3f5f0f800e26b9690bc/e10811ae"
    },
    "ELA M 260": {
        "phantom": "NO",
        "manufacturer": "Telefunken",
        "polar": ["Cardioid", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 120,
        "hasPad": false,
        "type": "SDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
        ],
        "char": [
            "Saturated",
            "Neutral",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/f7d2b8c9f53f21ed9366a029d547fe2b/7ff2413d"
    },
    "M80 SH": {
        "phantom": "NO",
        "manufacturer": "Telefunken",
        "polar": ["Cardioid"],
        "highestFreq": 18,
        "lowestFreq": 50,
        "SPL": 135,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Snare Drum",
        ],
        "char": [
            "Neutral",
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/e0b44b86977ff409c3abe0e4c0a4b98c/02cc9d83"
    },
    "M81 SH": {
        "phantom": "NO",
        "manufacturer": "Telefunken",
        "polar": ["Cardioid"],
        "highestFreq": 18,
        "lowestFreq": 50,
        "SPL": 135,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Toms",
        ],
        "char": [
            "Neutral",
            "Punchy",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/155ebbc57c42635b5f4eb88dfd745dae/f2c62c37"
    },
    "M82": {
        "phantom": "NO",
        "manufacturer": "Telefunken",
        "polar": ["Cardioid"],
        "highestFreq": 18,
        "lowestFreq": 25,
        "SPL": 146,
        "hasPad": false,
        "type": "Dynamic",
        "lendingLevel": 3,
        "uses": [
            "Electric Bass",
            "Kick",
        ],
        "char": [
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/fad2dfb1640b633cc1f1f8d69d9f58dd/9bcad163"
    },
    "WA-47": {
        "phantom": "NO",
        "manufacturer": "Warm Audio",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 140,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 4,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Trumpet/Sax/Horns",
            "Kick",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/aa8ed98cea907de41d8e804b2fcdabad/783c30df"
    },
    "WA-84": {
        "phantom": "YES",
        "manufacturer": "Warm Audio",
        "polar": ["Cardioid", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 133,
        "hasPad": true,
        "type": "SDC",
        "lendingLevel": 3,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Dark",
            "Saturated",
            "Smooth",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/ba5def0876b307fe98f60bb8d315f463/cc02037f"
    },
    
    "WA-87": {
        "phantom": "YES",
        "manufacturer": "Warm Audio",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 125,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": 2,
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Neutral",
        ],
        "img": "https://dl.airtable.com/.attachmentThumbnails/33a260bc7a0a2b03dbeff5640e7b3d9b/17f50f32"
    },
    "KSM44": {
        "phantom": "YES",
        "manufacturer": "Shure",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 156,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": "Not at SMC",
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Electric Bass",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Toms",
            "Hats/Cymbal Close Mics",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Transparent",
            "Punchy",
            "Smooth",
        ],
        "img": "https://media.sweetwater.com/api/i/f-webp__q-85__ha-11d53229e0052f80__hmac-aa208d84e82fafe98d2760703a5267ce977a7279/images/items/1800/KSM44A-xlarge.jpg.auto.webp"
    },
    "Origin": {
        "phantom": "YES",
        "manufacturer": "Aston",
        "polar": ["Cardioid"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 137,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": "Not at SMC",
        "uses": [
            "Acoustic Guitar",
            "Electric Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Kick",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Saturated",
            "Smooth",
        ],
        "img": "https://media.musiciansfriend.com/is/image/MMGS7/Origin-Cardioid-Condenser-Microphone/J32367000000000-00-500x500.jpg"
    },
    "BV12": {
        "phantom": "NO",
        "manufacturer": "Avantone",
        "polar": ["Cardioid", "Figure-8", "Omni"],
        "highestFreq": 20,
        "lowestFreq": 20,
        "SPL": 146,
        "hasPad": true,
        "type": "LDC",
        "lendingLevel": "Not at SMC",
        "uses": [
            "Acoustic Guitar",
            "Vocals",
            "Acoustic Piano",
            "Violin/Viola/Cello",
            "Trumpet/Sax/Horns",
            "Drum Overheads",
            "Drum Room",
            "General Purpose"
        ],
        "char": [
            "Bright",
            "Saturated",
            "Smooth",
        ],
        "img": "https://static.keymusic.com/products/261044/340/avantone-bv-12.jpg"
    },
    
}